package com.gto.app;

import java.util.List;

public final class Loadouts {

    private static final String PL = "[[[\"rhs_weap_m4_urgi_kac\",\"rhsusf_acc_nt4_tan\",\"rhsusf_acc_anpeq15side\",\"optic_Arco_blk_F\",[\"rhs_mag_30Rnd_556x45_M855A1_PMAG\",30],[],\"rhs_acc_m4_urgi_d\"],[],[\"rhsusf_weap_glock17g4\",\"\",\"acc_flashlight_pistol\",\"\",[\"rhsusf_mag_17Rnd_9x19_JHP\",17],[],\"\"],[\"TPW_G3_G3_FS_FM_UNIFORM_MCAMF\",[[\"ACE_EarPlugs\",1],[\"ACE_packingBandage\",30],[\"ACE_tourniquet\",4],[\"ACE_Flashlight_XL50\",1],[\"ACE_CableTie\",3],[\"ACE_IR_Strobe_Item\",1],[\"ACE_MapTools\",1],[\"ItemAndroid\",1],[\"ACE_painkillers\",1,10],[\"rhsusf_mag_17Rnd_9x19_JHP\",1,17]]],[\"3DMA_WD_AVS_PLLEAD\",[[\"ACE_HuntIR_monitor\",1],[\"ItemcTab\",1],[\"rhs_mag_30Rnd_556x45_M855A1_PMAG\",8,30],[\"ACE_M14\",3,1]]],[\"tfw_ilbe_blade_mc\",[[\"tfw_rf3080Item\",1],[\"SmokeShellBlue\",4,1],[\"SmokeShellGreen\",3,1],[\"ACE_M84\",2,1],[\"HandGrenade\",2,1],[\"SmokeShell\",8,1]]],\"3DMA_WD_Opscore_V5\",\"G_Squares_Tinted\",[\"Rangefinder\",\"\",\"\",\"\",[],[],\"\"],[\"ItemMap\",\"ItemGPS\",\"TFAR_anprc152\",\"ItemCompass\",\"ACE_Altimeter\",\"3DMA_WD_ANPVS31_v2\"]],[]]";
    private static final String Medic = "[[[\"rhs_weap_m4_urgi_kac\",\"rhsusf_acc_nt4_tan\",\"rhsusf_acc_anpeq15_wmx\",\"rhsusf_acc_su230\",[\"rhs_mag_30Rnd_556x45_M855A1_PMAG\",30],[],\"rhs_acc_m4_urgi_d\"],[],[\"rhsusf_weap_glock17g4\",\"\",\"acc_flashlight_pistol\",\"\",[\"rhsusf_mag_17Rnd_9x19_JHP\",17],[],\"\"],[\"TPW_G3_G3_FS_FM_UNIFORM_MCAMF_arfr\",[[\"ACE_EarPlugs\",1],[\"ACE_tourniquet\",4],[\"ACE_Flashlight_XL50\",1],[\"ACE_CableTie\",3],[\"ACE_IR_Strobe_Item\",1],[\"ItemAndroid\",1],[\"ACE_packingBandage\",30],[\"rhsusf_mag_17Rnd_9x19_JHP\",1,17],[\"ACE_painkillers\",1,10]]],[\"3DMA_WD_AVS_Medic\",[[\"SmokeShell\",2,1],[\"HandGrenade\",2,1],[\"rhs_mag_30Rnd_556x45_M855A1_PMAG\",8,30],[\"ACE_M84\",4,1]]],[\"B_TacticalPack_blk\",[[\"ACE_packingBandage\",40],[\"ACE_quikclot\",30],[\"ACE_epinephrine\",15],[\"ACE_adenosine\",10],[\"ACE_morphine\",8],[\"ACE_tourniquet\",5],[\"ACE_splint\",6],[\"ACE_salineIV\",6],[\"ACE_salineIV_500\",6],[\"ACE_salineIV_250\",4],[\"ACE_bodyBag\",1],[\"ACE_painkillers\",1,10]]],\"3DMA_WD_Opscore_V2\",\"rhs_googles_black\",[\"Rangefinder\",\"\",\"\",\"\",[],[],\"\"],[\"ItemMap\",\"\",\"TFAR_anprc152\",\"ItemCompass\",\"ACE_Altimeter\",\"3DMA_WD_ANPVS31_v2\"]],[]]";

    public static final List<String> list = List.of(PL, Medic);
}
